server:
  port: 19812
spring:
  config:
    import:
      - optional:classpath:config/application-athena.yaml
  datasource:
    url: jdbc:mysql://localhost:3306/note?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: false

lib:
  web:
    enumPackages:
      - 'org.athena.framework'
      - 'org.zzt.note'
