server:
  port: 19812
  servlet:
    context-path: /app-note
spring:
  config:
    import:
      - optional:application-athena.yaml
  profiles:
    default: dev
    group:
      dev:
        - local
      pro:
        - prod

logging:
  config: file:./config/logback-spring.xml
  level:
    root: DEBUG

app:
  log:
    level:
      app: INFO
      athena: WARN
      framework: ERROR
    threshold:
      console: DEBUG
      app: DEBUG
      athena: INFO
      framework: WARN
      all: DEBUG

lib:
  web:
    enumPackages:
      - 'org.athena.framework'
      - 'org.zzt.note'
