server:
  port: 19812
  servlet:
    context-path: /app-note
spring:
  config:
    import:
      - optional:application-athena.yaml
  profiles:
    default: dev
    group:
      dev:
        - local
      pro:
        - prod

lib:
  web:
    enumPackages:
      - 'org.athena.framework'
      - 'org.zzt.note'
